[package]
name = "cataclysm"
version = "0.2.0-beta.12"
license = "MIT"
description = "A simple http framework"
repository = "https://github.com/Malanche/cataclysm.git"
authors = ["Carlos Malanche <carlos.malanche.f@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
all-features = true

[features]
full_log = []
stream = []
ws = ["stream", "cataclysm-ws"]

[dev-dependencies]
criterion = {version = "0.3.5", features = ["async_tokio"]}
reqwest = "0.11.4"
colored = "2.0.0"
winapi = "0.3.9"
cataclysm-ws = {version = "0.2.0-beta.3", path = "../cataclysm-ws"}

[dependencies]
tokio = {version = "1.20.0", features = ["full"]}
ctrlc = "3.2.2"
regex = "1.6.0"
serde = {version = "1.0.139", features = ["derive"]}
serde_json = "1.0.82"
log = {version = "0.4.17", features = ["std"]}
futures = "0.3.21"
chrono = "0.4.19"
ring = "0.16.20"
base64 = "0.13.0"
cookie = {version = "0.16.0", features = ["percent-encode"]}
lazy_static = "1.4.0"
libflate = "1.2.0"
url = "2.2.2"
serde_qs = "0.10.1"
async-trait = "0.1.56"
bytes = "1.1.0"
cataclysm-ws = {version = "0.2.0-beta.3", path = "../cataclysm-ws", optional = true}

[[bench]]
name = "per_second"
harness = false